# Generated by Django 5.2.9 on 2025-12-06 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arenas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arenaimage',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='arenas.arena'),
        ),
        migrations.AddField(
            model_name='arena',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='arenas.city'),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='arenas.arena'),
        ),
        migrations.AddField(
            model_name='arena',
            name='sport_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arenas', to='arenas.sporttype'),
        ),
        migrations.AddField(
            model_name='workinghours',
            name='arena',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='arenas.arena'),
        ),
        migrations.AlterUniqueTogether(
            name='pricetable',
            unique_together={('arena', 'day_type')},
        ),
        migrations.AlterUniqueTogether(
            name='workinghours',
            unique_together={('arena', 'day_of_week')},
        ),
    ]
